services:
  wikipedia-parser:
    build: .
    depends_on:
      - neo4j
      - transmission
    network_mode: "host"
    volumes:
      - transmission-downloads:/downloads

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - USER=username
      - PASS=password
    volumes:
      - transmission-downloads:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

  neo4j:
    image: neo4j:latest
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - neo4j-data:/data
    env_file:
      - .env.neo4j
    restart: unless-stopped

volumes:
  neo4j-data:
  transmission-downloads: